spring:
  application:
    name: jpa-domain-modeling

  datasource:
    url: jdbc:mariadb://localhost:3306/localdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true